#!/usr/bin/env node

/**
 * This script starts up tixinc-js
 */

var log = require('bunyan').createLogger({name: 'tixinc-js-service'})
  , path = require('path')
  , exec = require('child_process').execFileSync
  , nodePath = path.join(__dirname, 'node.exe')
  , args = [path.join('bin', 'run')]
  , opts =  { cwd: path.join(__dirname, '..', 'tixinc-js')
            , stdio: 'inherit'
            , encoding: 'utf8'
            }
  , stdout = exec(nodePath, args, opts)

log.error(stdout, 'tixinc-js process died')
process.exit(1)
