#!/usr/bin/env node

var log = require('bunyan').createLogger({name: 'tixinc-net-service'})
  , path = require('path')
  , exec = require('child_process').execFileSync
  , serviceName = 'tixinc-net'
  , nssmPath = path.join(__dirname, 'nssm.exe')
  , exePath = path.join(__dirname, '..', 'tixinc-net', 'Tix.Web.SelfHost.exe')
  , commandArgs = { install: ['install', serviceName, exePath]
                  , uninstall: ['remove', serviceName, 'confirm']
                  , setDescription:  ['set', serviceName, 'Description', 'The tixinc-net ASP.NET WebApi authorization and resource server.']
                  , start: ['start', serviceName]
                  , stop: ['stop', serviceName]
                  , restart: ['restart', serviceName]
                  , status: ['status', serviceName]
                  }

function nssm(args) {
  return exec(nssmPath, args, { stdio: 'inherit'
                              , encoding: 'utf8'
                              })
}

log.info('uninstalling tixinc-net')
nssm(commandArgs.stop)
nssm(commandArgs.uninstall)
log.info('tixinc-net uninstalled successfully')

