#!/usr/bin/env node

var log = require('bunyan').createLogger({name: 'tixinc-js-service'})
  , path = require('path')
  , Service = require('node-windows').Service
  , scriptPath = path.join(__dirname, 'tixinc-js-start')
  , opts = { name:'tixinc-js'
           , description: 'The tixinc-js node.js host for angular, scripts, and other assets.'
           , script: scriptPath
           }
  , srv = new Service(opts)


srv.on('install',function(){
  log.info('tixinc-js install complete, starting')
  srv.start()
})

srv.on('error', function(error) {
  log.error(error, 'tixinc-js error occurred')
})

log.info(opts, 'installing tixinc-js service')
srv.install()