#!/usr/bin/env node

var log = require('bunyan').createLogger({name: 'tixinc-js-service'})
  , path = require('path')
  , Service = require('node-windows').Service
  , scriptPath = path.join(__dirname, 'tixinc-js-start')
  , opts =  { name:'tixinc-js'
            , description: 'The tixinc-js node.js host for angular, scripts, and other assets.'
            , script: scriptPath
            }
  , srv = new Service(opts)

srv.on('uninstall',function(){
  log.info('tixinc-js uninstalled successfully')
})
srv.uninstall()
